name: Install and Configure Auditd
hosts: linux
become: yes
strategy: free
tasks:
  - name: Install Auditd
    ansible.builtin.package:
      name: "auditd"
      state: "present"

  - name: Install Florian Roth Rules
    ansible.builtin.copy:
      src: "florian.rules"
      dest: "/etc/audit/rules.d/"

  - name: Restart Auditd
    ansible.builtin.service:
      name: "auditd"
      enabled: true
      state: "restarted"
