# Do Firewall Stuff

# Allow only the team IP Addresses into the network
- name: Network Blackout
  hosts: all
  roles:
    - blackout
  tags:
    - network_blackout

# Distribute host based Firewall Rules
- name: Add Firewall Rules
  hosts: all
  roles:
    - add_rules
  tags:
    - setup
